/* IELTS Writing Lab — Task 1 chart bank
 * Each scenario describes a realistic exam topic. Numbers are generated
 * fresh every time (see charts.js), so the same topic never repeats exactly.
 *
 * type: 'line' | 'bar' | 'pie' | 'table' | 'mixed'
 * series: things being compared (countries, products…)
 * cats:   x-axis categories (years or groups)
 * range:  [min, max] for generated values
 * unit:   label for the values ('%', 'millions', '$'…)
 * step:   rounding step for values
 */
const TASK1_BANK = [
  // ───────────── LINE (12) ─────────────
  { id:'l1', type:'line', unit:'%', step:1, range:[5,95],
    para:'how many households had an internet connection in four countries', ent:'countries',
    title:'Percentage of households with internet access in four countries',
    series:['USA','Germany','Brazil','India','Japan','South Africa'], pick:4,
    cats:[2000,2005,2010,2015,2020] },
  { id:'l2', type:'line', unit:'millions', step:0.5, range:[2,40],
    para:'how many overseas visitors travelled to three countries', ent:'countries',
    title:'Number of international tourists visiting three countries',
    series:['France','Thailand','Egypt','Mexico','Australia'], pick:3,
    cats:[1995,2000,2005,2010,2015,2020] },
  { id:'l3', type:'line', unit:'%', step:1, range:[2,20],
    para:'the proportion of people without a job in four European nations', ent:'countries',
    title:'Unemployment rates in four European countries',
    series:['Spain','Greece','Germany','UK','Italy','Sweden'], pick:4,
    cats:[2008,2010,2012,2014,2016,2018,2020] },
  { id:'l4', type:'line', unit:'kg per person', step:1, range:[10,120],
    para:'how much of three different foods a person ate each year in a European country', ent:'food types',
    title:'Annual consumption of three types of food per person in a European country',
    series:['Beef','Chicken','Fish','Pork','Lamb'], pick:3,
    cats:[1980,1990,2000,2010,2020] },
  { id:'l5', type:'line', unit:'thousands', step:5, range:[20,500],
    para:'how many cars three different manufacturers made', ent:'companies',
    title:'Number of cars produced by three manufacturers',
    series:['Company A','Company B','Company C','Company D'], pick:3,
    cats:[2010,2012,2014,2016,2018,2020,2022] },
  { id:'l6', type:'line', unit:'%', step:1, range:[5,60],
    para:'the share of elderly people in the population of three nations', ent:'countries',
    title:'Proportion of the population aged 65 and over in three countries',
    series:['Japan','Italy','USA','Nigeria','Brazil'], pick:3,
    cats:[1960,1980,2000,2020,2040] },
  { id:'l7', type:'line', unit:'million tonnes', step:1, range:[5,80],
    para:'the quantity of carbon dioxide released by four sectors in a country', ent:'sectors',
    title:'CO2 emissions from four sectors in a country',
    series:['Transport','Industry','Households','Agriculture','Energy production'], pick:4,
    cats:[1990,1995,2000,2005,2010,2015,2020] },
  { id:'l8', type:'line', unit:'$ per week', step:5, range:[20,250],
    para:'how much money British households spent each week on four types of goods', ent:'categories',
    title:'Average weekly spending on four categories by UK households',
    series:['Food','Transport','Recreation','Clothing','Housing'], pick:4,
    cats:[1990,2000,2010,2020] },
  { id:'l9', type:'line', unit:'thousands', step:1, range:[5,120],
    para:'how many students studied three different subjects at a university', ent:'courses',
    title:'Number of students enrolled in three courses at a university',
    series:['Business','Engineering','Arts','Computer Science','Medicine'], pick:3,
    cats:[2005,2008,2011,2014,2017,2020] },
  { id:'l10', type:'line', unit:'minutes per day', step:5, range:[10,240],
    para:'how many minutes a day adults devoted to three media activities', ent:'activities',
    title:'Average time spent on three media activities per day by adults',
    series:['Watching TV','Using the internet','Reading newspapers','Listening to radio'], pick:3,
    cats:[2000,2005,2010,2015,2020] },
  { id:'l11', type:'line', unit:'litres per person per day', step:5, range:[50,400],
    para:'the daily amount of water used per person in four cities', ent:'cities',
    title:'Water consumption per person in four cities',
    series:['Sydney','Cairo','London','Mumbai','Toronto'], pick:4,
    cats:[1990,2000,2010,2020] },
  { id:'l12', type:'line', unit:'%', step:1, range:[1,45],
    para:'the share of workers travelling to work by different means of transport in a city', ent:'modes of transport',
    title:'Percentage of people using different types of transport to get to work in a city',
    series:['Car','Bus','Bicycle','Train','Walking'], pick:4,
    cats:[1980,1990,2000,2010,2020] },

  // ───────────── BAR (10) ─────────────
  { id:'b1', type:'bar', unit:'%', step:1, range:[5,80],
    para:'the share of adults in six age groups who took part in sport', ent:'age groups',
    title:'Percentage of adults who participated in sport, by age group',
    series:['2005','2020'],
    cats:['16-24','25-34','35-44','45-54','55-64','65+'] },
  { id:'b2', type:'bar', unit:'million tonnes', step:1, range:[5,120],
    para:'the quantity of rice sold abroad by five countries', ent:'countries',
    title:'Amount of rice exported by five countries',
    series:['2010','2020'],
    cats:['India','Thailand','Vietnam','Pakistan','USA'] },
  { id:'b3', type:'bar', unit:'%', step:1, range:[5,70],
    para:'why adults of different ages chose to study', ent:'age groups',
    title:'Reasons given by adults for studying, by age group',
    series:['Interest in subject','Career prospects'],
    cats:['Under 26','26-29','30-39','40-49','Over 49'] },
  { id:'b4', type:'bar', unit:'$ billions', step:1, range:[2,60],
    para:'how much Australia earned from exports in four sectors', ent:'sectors',
    title:'Value of exports in four categories from Australia',
    series:['2000','2010','2020'],
    cats:['Minerals','Agriculture','Manufacturing','Services'] },
  { id:'b5', type:'bar', unit:'hours per week', step:1, range:[2,40],
    para:'the weekly time men and women in five countries devoted to household chores', ent:'countries',
    title:'Average hours spent on housework by men and women in five countries',
    series:['Men','Women'],
    cats:['Japan','Sweden','USA','Mexico','India'] },
  { id:'b6', type:'bar', unit:'thousands', step:5, range:[10,300],
    para:'how many people visited four museums in London', ent:'museums',
    title:'Number of visitors to four museums in London',
    series:['2015','2020'],
    cats:['British Museum','Science Museum','Natural History Museum','Tate Modern'] },
  { id:'b7', type:'bar', unit:'%', step:1, range:[5,60],
    para:'the share of electricity generated from renewable sources in six countries', ent:'countries',
    title:'Percentage of energy produced from renewable sources in six countries',
    series:['2010','2020'],
    cats:['Norway','Brazil','Germany','China','USA','Australia'] },
  { id:'b8', type:'bar', unit:'%', step:1, range:[5,70],
    para:'the share of male and female graduates employed in five sectors a year after finishing university', ent:'sectors',
    title:'Proportion of graduates working in different sectors one year after graduating',
    series:['Male','Female'],
    cats:['Business','Education','Health','Engineering','Arts & Media'] },
  { id:'b9', type:'bar', unit:'kg', step:5, range:[20,400],
    para:'how much waste each household recycled per year in four countries', ent:'countries',
    title:'Amount of waste recycled per household per year in four countries',
    series:['2005','2015'],
    cats:['Germany','South Korea','UK','USA'] },
  { id:'b10', type:'bar', unit:'%', step:1, range:[5,60],
    para:'the share of people in three income groups who ate fast food at least weekly', ent:'income groups',
    title:'Percentage of people who eat fast food more than once a week, by income group',
    series:['2010','2020'],
    cats:['Low income','Middle income','High income'] },

  // ───────────── PIE (6) ─────────────
  { id:'p1', type:'pie', unit:'%', step:1,
    para:'where Australia\'s electricity came from', ent:'energy sources',
    title:'Sources of electricity production in Australia',
    series:['1980','2020'],
    cats:['Coal','Natural gas','Hydro','Solar & wind','Oil'] },
  { id:'p2', type:'pie', unit:'%', step:1,
    para:'the means of transport students used to reach the university', ent:'modes of transport',
    title:'How students at a university travel to campus',
    series:['2000','2020'],
    cats:['Car','Bus','Bicycle','Walking','Train'] },
  { id:'p3', type:'pie', unit:'%', step:1,
    para:'how a typical family divided its spending between different items', ent:'categories',
    title:'Spending of an average family on different items',
    series:['1990','2020'],
    cats:['Housing','Food','Transport','Entertainment','Clothing','Other'] },
  { id:'p4', type:'pie', unit:'%', step:1,
    para:'why men and women chose to relocate to a different city', ent:'reasons',
    title:'Main reasons for people moving to a new city',
    series:['Men','Women'],
    cats:['Employment','Education','Family','Lifestyle','Housing costs'] },
  { id:'p5', type:'pie', unit:'%', step:1,
    para:'the kinds of waste generated by a city', ent:'waste types',
    title:'Types of waste produced by a city',
    series:['2005','2020'],
    cats:['Paper','Plastic','Food','Glass','Metal','Other'] },
  { id:'p6', type:'pie', unit:'%', step:1,
    para:'how global mobile phone sales were divided between manufacturers', ent:'brands',
    title:'Share of global mobile phone sales by manufacturer',
    series:['2012','2022'],
    cats:['Brand A','Brand B','Brand C','Brand D','Others'] },

  // ───────────── TABLE (6) ─────────────
  { id:'t1', type:'table', unit:'thousands', step:1, range:[2,80],
    para:'how many overseas students were enrolled at five universities', ent:'universities',
    title:'Number of international students in five universities',
    series:['2015','2020'],
    cats:['University A','University B','University C','University D','University E'] },
  { id:'t2', type:'table', unit:'%', step:1, range:[5,60],
    para:'the share of people living in cities in six countries', ent:'countries',
    title:'Percentage of the population living in urban areas in six countries',
    series:['1990','2020'],
    cats:['China','India','Brazil','Nigeria','Indonesia','Egypt'] },
  { id:'t3', type:'table', unit:'$', step:10, range:[300,3500],
    para:'the typical monthly cost of renting a one-bedroom flat in five cities', ent:'cities',
    title:'Average monthly rent for a one-bedroom apartment in five cities',
    series:['2010','2020'],
    cats:['New York','London','Tokyo','Berlin','Bangkok'] },
  { id:'t4', type:'table', unit:'minutes', step:1, range:[10,90],
    para:'how long people in five cities spent travelling to work each day', ent:'cities',
    title:'Average daily commuting time in five cities',
    series:['Car','Public transport'],
    cats:['Los Angeles','Paris','Singapore','Mumbai','Sydney'] },
  { id:'t5', type:'table', unit:'%', step:1, range:[10,95],
    para:'the proportion of men and women who could read and write in five regions', ent:'regions',
    title:'Literacy rates for men and women in five regions',
    series:['Men','Women'],
    cats:['East Asia','South Asia','Sub-Saharan Africa','Latin America','Europe'] },
  { id:'t6', type:'table', unit:'millions', step:0.5, range:[1,30],
    para:'how many passengers passed through four airports', ent:'airports',
    title:'Number of passengers using four airports',
    series:['2000','2010','2020'],
    cats:['Airport A','Airport B','Airport C','Airport D'] },

  // ───────────── MIXED bar + line (4) ─────────────
  { id:'m1', type:'mixed', step:1,
    para:'how many people visited a museum and how much a ticket cost', ent:'measures',
    title:'Number of visitors to a museum and the average ticket price',
    bar:{name:'Visitors', unit:'thousands', range:[50,400]},
    line:{name:'Ticket price', unit:'$', range:[5,30]},
    cats:[2012,2014,2016,2018,2020,2022] },
  { id:'m2', type:'mixed', step:1,
    para:'how many homes were constructed in a city and the typical price of a house', ent:'measures',
    title:'Number of new houses built in a city and the average house price',
    bar:{name:'Houses built', unit:'thousands', range:[5,60]},
    line:{name:'Average price', unit:'$ thousands', range:[100,600]},
    cats:[2000,2005,2010,2015,2020] },
  { id:'m3', type:'mixed', step:1,
    para:'the amount of rain and the average temperature in a city across the year', ent:'measures',
    title:'Rainfall and average temperature in a city by month',
    bar:{name:'Rainfall', unit:'mm', range:[10,250]},
    line:{name:'Temperature', unit:'°C', range:[5,35]},
    cats:['Jan','Mar','May','Jul','Sep','Nov'] },
  { id:'m4', type:'mixed', step:1,
    para:'the size of a company\'s workforce and how much profit it made', ent:'measures',
    title:'Number of employees at a company and its annual profit',
    bar:{name:'Employees', unit:'thousands', range:[1,25]},
    line:{name:'Profit', unit:'$ millions', range:[2,120]},
    cats:[2010,2012,2014,2016,2018,2020] },
];
